#!/bin/bash
# I3 fig setup
#after main setup
#theming

cd
mkdir i3themes
cd i3themes
wget https://github.com/harry963/i3fig/blob/master/arch.png


#fonts
wget https://github.com/harry963/i3fig/blob/master/HackTTF.zip
unzip HackTTF.zip
cd ttf
mkdir ~/.fonts/
mv *.tff ~/.fonts/
cd ~/i3themes



#termite stuff
#wget https://github.com/harry963/i3fig/blob/master/Tconfig
#mkdir ~/.config/termite/
#cd ~/.config/termite/
#cp ~/i3themes/Tconfig ~/.config/termite/config
#cd ~/i3themes

#Gedit
wget https://raw.githubusercontent.com/dracula/gedit/master/dracula.xml
mkdir $HOME/.local/share/gedit/styles/
mv dracula.xml $HOME/.local/share/gedit/styles/
cd ~/i3themes 
#i3blocks

sudo mkdir /usr/share/i3blocks/
mkdir ~/i3themes/i3blocks/
cd ~/i3themes
wget https://github.com/harry963/i3fig/blob/master/i3blocks.conf
cd ~/i3themes

#i3 fig
cd ~/i3themes
wget https://github.com/harry963/i3fig/blob/master/i3config
cp i3config ~/.config/i3/config

