#!/bin/bash
# I3 fig setup
# after main setup
# theming
cd
# fonts
cd i3fig
unzip HackTTF.zip
cd ttf
mkdir ~/.fonts/
mv *.ttf ~/.fonts/
cd ~/i3fig
# termite stuff
mkdir ~/.config/termite/
cd ~/.config/termite/
cp ~/i3fig/Tconfig ~/.config/termite/config
cd ~/i3fig
#alacritty (the working terminal)
mkdir ~/.config/alacritty
cp ~/i3fig/alacritty.yml ~/.config/alacritty/alacritty.yml
# Polybar
chmod +x ~/i3fig/launch.sh
mkdir ~/.config/polybar
cp $HOME/i3fig/launch.sh  $HOME/.config/polybar/launch.sh
cp ~/i3fig/polybarconfig ~/.config/polybar/config
# i3 fig
mkdir ~/.config/i3/
cp ~/i3fig/i3config ~/.config/i3/config
cd ~/i3fig
# GTK theme
unzip gtk-master.zip
mkdir ~/.themes/
cp -r gtk-master ~/.themes/dracula
sudo cp -r gtk-master /usr/share/themes/
echo run the following
echo sudo cp -r gtk-master /usr/share/themes/
