#!/bin/sh
#first install tlp
sudo pacman -S tlp tlp-rdw
#enable services
sudo systemctl enable tlp.service
sudo systemctl enable tlp-sleep.service
sudo systemctl mask systemd-rfkill.service
sudo systemctl mask systemd-rfkill.socket
sudo tlp start
sudo cp tlp.conf /etc/tlp.conf
echo ........
echo ........
echo ........
echo in /etc/tlp.conf add these lines
echo SATA_LINKPWR_ON_BAT=max_performance
